# Generated by Django 5.1.4 on 2025-01-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='work_expert',
            new_name='work_experience',
        ),
    ]
