# Generated by Django 5.1.4 on 2025-01-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_rename_work_expert_teacher_work_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_expert',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
    ]
