# Generated by Django 5.1.4 on 2025-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_teacher_work_experience_teacher_work_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='work_expert',
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
