# Generated by Django 5.1.4 on 2025-01-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_teachers'),
        ('teachers', '0002_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_teacher', to='teachers.teacher'),
        ),
    ]
