# Generated by Django 5.1.4 on 2025-01-17 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_teachers'),
        ('teachers', '0002_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teachers',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=255),
        ),
    ]
